// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CountButton: typeof import('./components/CountDown/CountButton.vue')['default']
    CountdownInput: typeof import('./components/CountDown/CountdownInput.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RightContent: typeof import('./components/RightContent/RightContent.vue')['default']
    SettingDrawer: typeof import('./components/SettingDrawer/index.vue')['default']
    WelCome: typeof import('./components/WelCome.vue')['default']
  }
}

export { }
